"""
Recruiter API endpoints
"""
from fastapi import APIRouter, HTTPException, Depends, Query, Path
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
from typing import List, Dict, Optional

from app.core.database import get_db
from app.api.dependencies import get_current_user
from app.models.user import User, UserRole
from app.models.reports import Report
from app.models.interview import InterviewSession

router = APIRouter()


def get_current_recruiter(current_user: User = Depends(get_current_user)):
    """Dependency to check if user is a recruiter or admin"""
    if current_user.role not in (UserRole.RECRUITER.value, UserRole.ADMIN.value):
        raise HTTPException(status_code=403, detail="Not authorized to access recruiter endpoints")
    return current_user


@router.get("/candidates", summary="Get all candidates")
async def get_candidates(
    current_recruiter: User = Depends(get_current_recruiter),
    db: AsyncSession = Depends(get_db)
):
    """Get list of candidates (users with role=candidate)"""
    query = select(User).where(User.role == UserRole.CANDIDATE.value)
    result = await db.execute(query)
    candidates = result.scalars().all()
    
    return [
        {
            "id": c.id,
            "email": c.email,
            "first_name": c.first_name,
            "last_name": c.last_name,
            "created_at": c.created_at
        }
        for c in candidates
    ]


@router.get("/dashboard", summary="Recruiter dashboard metrics")
async def get_dashboard(
    current_recruiter: User = Depends(get_current_recruiter),
    db: AsyncSession = Depends(get_db)
):
    """
    Get metrics for recruiter dashboard quick comparison table.
    Groups reports by candidate and returns latest metrics.
    """
    # Fetch all completed reports
    query = select(Report, User).join(User, Report.user_id == User.id).where(
        User.role == UserRole.CANDIDATE.value
    ).order_by(Report.created_at.desc())
    
    result = await db.execute(query)
    rows = result.all()
    
    # Get latest report per candidate
    seen_users = set()
    dashboard_data = []
    
    for report, user in rows:
        if user.id in seen_users:
            continue
        seen_users.add(user.id)
        
        data = report.data or {}
        radar = data.get("radar_data", {})
        
        # Determine recommendation based on readiness
        readiness = data.get("readiness_score", 0)
        if readiness >= 80:
            rec = "Recommended"
        elif readiness >= 60:
            rec = "Recommended with Training"
        else:
            rec = "Not Recommended"
            
        dashboard_data.append({
            "candidate_id": user.id,
            "name": f"{user.first_name} {user.last_name}".strip() or user.email,
            "readiness_score": readiness,
            "technical_score": radar.get("technical", 0),
            "communication_score": radar.get("communication", 0),
            "integrity_score": data.get("integrity_score", radar.get("integrity", 100)),
            "recommendation": data.get("hiring_recommendation", rec),
            "latest_report_id": report.id,
            "latest_session_id": report.session_id,
            "interview_date": report.created_at
        })
        
    return dashboard_data


@router.get("/reports", summary="Get all reports")
async def get_all_reports(
    current_recruiter: User = Depends(get_current_recruiter),
    db: AsyncSession = Depends(get_db)
):
    """Get all reports generated by candidates"""
    query = select(Report).order_by(Report.created_at.desc())
    result = await db.execute(query)
    reports = result.scalars().all()
    
    return [
        {
            "id": r.id,
            "session_id": r.session_id,
            "user_id": r.user_id,
            "report_type": r.report_type,
            "created_at": r.created_at,
            "data": r.data
        }
        for r in reports
    ]


@router.get("/reports/{candidate_id}", summary="Get reports for a specific candidate")
async def get_candidate_reports(
    candidate_id: str = Path(...),
    current_recruiter: User = Depends(get_current_recruiter),
    db: AsyncSession = Depends(get_db)
):
    """Get all reports for a specific candidate"""
    query = select(Report).where(Report.user_id == candidate_id).order_by(Report.created_at.desc())
    result = await db.execute(query)
    reports = result.scalars().all()
    
    return [
        {
            "id": r.id,
            "session_id": r.session_id,
            "report_type": r.report_type,
            "created_at": r.created_at,
            "data": r.data
        }
        for r in reports
    ]
