"""
add_ai_tables

Revision ID: 332f46b752fd
Revises: 001_initial
Create Date: 2026-06-24 20:37:57.307870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '332f46b752fd'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('domain', sa.String(length=50), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('question_type', sa.String(length=30), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('follow_up_prompts', sa.JSON(), nullable=True),
    sa.Column('ideal_answer_outline', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analytics_snapshots',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('session_count', sa.Integer(), nullable=True),
    sa.Column('avg_overall_score', sa.Float(), nullable=True),
    sa.Column('avg_technical_score', sa.Float(), nullable=True),
    sa.Column('avg_communication_score', sa.Float(), nullable=True),
    sa.Column('avg_confidence_score', sa.Float(), nullable=True),
    sa.Column('avg_eye_contact_pct', sa.Float(), nullable=True),
    sa.Column('domain_scores', sa.JSON(), nullable=True),
    sa.Column('improvement_delta', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_snapshots_user_id'), 'analytics_snapshots', ['user_id'], unique=False)
    op.create_table('analysis_jobs',
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('current_step', sa.String(length=100), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_jobs_celery_task_id'), 'analysis_jobs', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_session_id'), 'analysis_jobs', ['session_id'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_status'), 'analysis_jobs', ['status'], unique=False)
    op.create_table('coaching_events',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp_ms', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('trigger_metric', sa.JSON(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coaching_events_session_id'), 'coaching_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_coaching_events_timestamp_ms'), 'coaching_events', ['timestamp_ms'], unique=False)
    op.create_table('communication_scores',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('grammar_score', sa.Float(), nullable=True),
    sa.Column('vocabulary_score', sa.Float(), nullable=True),
    sa.Column('clarity_score', sa.Float(), nullable=True),
    sa.Column('fluency_score', sa.Float(), nullable=True),
    sa.Column('discourse_score', sa.Float(), nullable=True),
    sa.Column('structure_score', sa.Float(), nullable=True),
    sa.Column('star_method_used', sa.Boolean(), nullable=True),
    sa.Column('overall_communication_score', sa.Float(), nullable=True),
    sa.Column('improvement_suggestions', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_scores_session_id'), 'communication_scores', ['session_id'], unique=False)
    op.create_table('confidence_timeline',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp_ms', sa.Integer(), nullable=False),
    sa.Column('vocal_confidence', sa.Float(), nullable=True),
    sa.Column('visual_confidence', sa.Float(), nullable=True),
    sa.Column('fused_confidence', sa.Float(), nullable=True),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_confidence_timeline_session_id'), 'confidence_timeline', ['session_id'], unique=False)
    op.create_index(op.f('ix_confidence_timeline_timestamp_ms'), 'confidence_timeline', ['timestamp_ms'], unique=False)
    op.create_table('emotion_timeline',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp_ms', sa.Integer(), nullable=False),
    sa.Column('text_emotion', sa.String(length=20), nullable=True),
    sa.Column('face_emotion', sa.String(length=20), nullable=True),
    sa.Column('fused_emotion', sa.String(length=20), nullable=True),
    sa.Column('text_emotion_scores', sa.JSON(), nullable=True),
    sa.Column('face_emotion_scores', sa.JSON(), nullable=True),
    sa.Column('intensity', sa.Float(), nullable=True),
    sa.Column('is_congruent', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emotion_timeline_session_id'), 'emotion_timeline', ['session_id'], unique=False)
    op.create_index(op.f('ix_emotion_timeline_timestamp_ms'), 'emotion_timeline', ['timestamp_ms'], unique=False)
    op.create_table('eye_tracking_data',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('eye_contact_pct', sa.Float(), nullable=True),
    sa.Column('avg_contact_duration_ms', sa.Float(), nullable=True),
    sa.Column('gaze_stability_score', sa.Float(), nullable=True),
    sa.Column('gaze_distribution', sa.JSON(), nullable=True),
    sa.Column('gaze_off_events', sa.JSON(), nullable=True),
    sa.Column('fixation_count', sa.Integer(), nullable=True),
    sa.Column('distraction_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eye_tracking_data_session_id'), 'eye_tracking_data', ['session_id'], unique=False)
    op.create_table('face_metrics',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('face_visibility_pct', sa.Float(), nullable=True),
    sa.Column('avg_confidence_score', sa.Float(), nullable=True),
    sa.Column('smile_index', sa.Float(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('dominant_expression', sa.String(length=30), nullable=True),
    sa.Column('expression_timeline', sa.JSON(), nullable=True),
    sa.Column('head_pose_summary', sa.JSON(), nullable=True),
    sa.Column('blink_rate_per_minute', sa.Float(), nullable=True),
    sa.Column('frame_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_metrics_session_id'), 'face_metrics', ['session_id'], unique=False)
    op.create_table('interview_questions',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('asked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('answer_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('was_follow_up', sa.Boolean(), nullable=True),
    sa.Column('parent_question_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_question_id'], ['interview_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_questions_session_id'), 'interview_questions', ['session_id'], unique=False)
    op.create_table('proctoring_alerts',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('timestamp_ms', sa.Integer(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proctoring_alerts_session_id'), 'proctoring_alerts', ['session_id'], unique=False)
    op.create_table('proctoring_sessions',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('total_alerts', sa.Integer(), nullable=True),
    sa.Column('critical_alerts', sa.Integer(), nullable=True),
    sa.Column('proctoring_mode', sa.String(length=20), nullable=True),
    sa.Column('tab_switches', sa.Integer(), nullable=True),
    sa.Column('gaze_off_duration_ms', sa.Integer(), nullable=True),
    sa.Column('multi_face_events', sa.Integer(), nullable=True),
    sa.Column('verdict', sa.String(length=20), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('reports',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('report_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_session_id'), 'reports', ['session_id'], unique=False)
    op.create_index(op.f('ix_reports_share_token'), 'reports', ['share_token'], unique=True)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    op.create_table('responses',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('transcript_text', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('video_clip_url', sa.String(length=500), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['interview_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_responses_question_id'), 'responses', ['question_id'], unique=False)
    op.create_index(op.f('ix_responses_session_id'), 'responses', ['session_id'], unique=False)
    op.create_table('speech_metrics',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('response_id', sa.String(length=36), nullable=True),
    sa.Column('words_per_minute', sa.Float(), nullable=True),
    sa.Column('total_words', sa.Integer(), nullable=True),
    sa.Column('total_duration_seconds', sa.Float(), nullable=True),
    sa.Column('pause_count', sa.Integer(), nullable=True),
    sa.Column('avg_pause_duration_ms', sa.Float(), nullable=True),
    sa.Column('filler_count', sa.Integer(), nullable=True),
    sa.Column('filler_words', sa.JSON(), nullable=True),
    sa.Column('filler_rate_per_minute', sa.Float(), nullable=True),
    sa.Column('fluency_score', sa.Float(), nullable=True),
    sa.Column('clarity_score', sa.Float(), nullable=True),
    sa.Column('pronunciation_score', sa.Float(), nullable=True),
    sa.Column('grammar_score', sa.Float(), nullable=True),
    sa.Column('vocabulary_richness', sa.Float(), nullable=True),
    sa.Column('grammar_issues', sa.JSON(), nullable=True),
    sa.Column('prosody', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['response_id'], ['responses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speech_metrics_session_id'), 'speech_metrics', ['session_id'], unique=False)
    op.create_table('technical_scores',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('response_id', sa.String(length=36), nullable=True),
    sa.Column('question_id', sa.String(length=36), nullable=True),
    sa.Column('accuracy_score', sa.Float(), nullable=True),
    sa.Column('depth_score', sa.Float(), nullable=True),
    sa.Column('completeness_score', sa.Float(), nullable=True),
    sa.Column('examples_score', sa.Float(), nullable=True),
    sa.Column('industry_language_score', sa.Float(), nullable=True),
    sa.Column('overall_technical_score', sa.Float(), nullable=True),
    sa.Column('llm_feedback', sa.Text(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('missing_concepts', sa.JSON(), nullable=True),
    sa.Column('llm_model_used', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['interview_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_id'], ['responses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technical_scores_session_id'), 'technical_scores', ['session_id'], unique=False)
    op.create_table('transcripts',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('response_id', sa.String(length=36), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('word_timestamps', sa.JSON(), nullable=True),
    sa.Column('segments', sa.JSON(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['response_id'], ['responses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcripts_session_id'), 'transcripts', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcripts_session_id'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index(op.f('ix_technical_scores_session_id'), table_name='technical_scores')
    op.drop_table('technical_scores')
    op.drop_index(op.f('ix_speech_metrics_session_id'), table_name='speech_metrics')
    op.drop_table('speech_metrics')
    op.drop_index(op.f('ix_responses_session_id'), table_name='responses')
    op.drop_index(op.f('ix_responses_question_id'), table_name='responses')
    op.drop_table('responses')
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_share_token'), table_name='reports')
    op.drop_index(op.f('ix_reports_session_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_table('proctoring_sessions')
    op.drop_index(op.f('ix_proctoring_alerts_session_id'), table_name='proctoring_alerts')
    op.drop_table('proctoring_alerts')
    op.drop_index(op.f('ix_interview_questions_session_id'), table_name='interview_questions')
    op.drop_table('interview_questions')
    op.drop_index(op.f('ix_face_metrics_session_id'), table_name='face_metrics')
    op.drop_table('face_metrics')
    op.drop_index(op.f('ix_eye_tracking_data_session_id'), table_name='eye_tracking_data')
    op.drop_table('eye_tracking_data')
    op.drop_index(op.f('ix_emotion_timeline_timestamp_ms'), table_name='emotion_timeline')
    op.drop_index(op.f('ix_emotion_timeline_session_id'), table_name='emotion_timeline')
    op.drop_table('emotion_timeline')
    op.drop_index(op.f('ix_confidence_timeline_timestamp_ms'), table_name='confidence_timeline')
    op.drop_index(op.f('ix_confidence_timeline_session_id'), table_name='confidence_timeline')
    op.drop_table('confidence_timeline')
    op.drop_index(op.f('ix_communication_scores_session_id'), table_name='communication_scores')
    op.drop_table('communication_scores')
    op.drop_index(op.f('ix_coaching_events_timestamp_ms'), table_name='coaching_events')
    op.drop_index(op.f('ix_coaching_events_session_id'), table_name='coaching_events')
    op.drop_table('coaching_events')
    op.drop_index(op.f('ix_analysis_jobs_status'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_session_id'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_celery_task_id'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    op.drop_index(op.f('ix_analytics_snapshots_user_id'), table_name='analytics_snapshots')
    op.drop_table('analytics_snapshots')
    op.drop_table('questions')
    # ### end Alembic commands ###
