apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: holistic-interview
spec:
  selector:
    app: holistic-interview
    component: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
